DWH-CDP-URL='jdbc:impala://coordinator-cdp-cdw-live.dw-aws-bi-live.vaxy-y10l.cloudera.site:443/default;AuthMech=3;transportMode=http;httpPath=cliservice;ssl=1;'
DWH-CDP-PASSWORD='CnJs@1921!'
DWH-CDP-USER='cameron.jones'
DWH-CDP-JCLASSNAME='com.cloudera.impala.jdbc.DataSource'
DWH-CDP-JARPATH='/Users/cameronjones/PycharmProjects/Automation/web/incidents_web/app/jars/ImpalaJDBC42.jar'
