# test yml file for deploying streamlit app to kubernetes
name: streamlit web live

env:
  APP_NAME: uk-incidents-tool
  CHART_VERSION: 0.1.0
  KUBERNETES_NAMESPACE: uk-csa-data-product-live
  ARTIFACTORY_REGISTRY: repo.tools-k8s.hellofresh.io
  IMAGE_PATH: uk-csa-data-product-live/latest
  # not entirely sure if this is the correct path - added it to the docker image to the AWS ECR
  # under the repo name uk-csa-data-product-live and the tag latest. within eu-west-1 region


  APP_URL: uk-incidents-tool.dwh.hellofresh.io
  # do I need to set this somewhere? or is it automatically set via this command?

jobs:
  build-docker:
    runs-on: [self-hosted, default]
    strategy:
      max-parallel: 1